server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: document-processor-data
  profiles:
    include:
      - lot-sizes
  datasource:
     url: jdbc:postgresql://postgresql.dev.svc.cluster.local:5432/portfolio
     username: postgres
     password: password
     driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: kafka.dev.svc.cluster.local:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaUser" password="kafkaPassword123!";
    consumer:
      group-id: document-processor
      auto-offset-reset: earliest
  data:
    mongodb:
      auto-index-creation: true

app:
  kafka:
    portfolio-topic: am-portfolio
    trade-topic: am-trade
  persistence:
    mongodb:
      uri: mongodb://admin:password@mongodb.dev.svc.cluster.local:27017/nse_security?authSource=admin
      database: nse_security

logging:
  level:
    root: INFO
    org.am.mypotrfolio: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG