server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: document-processor-data
  datasource:
     url: jdbc:postgresql://localhost:5432/postgres
     username: postgres
     password: password
     driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: document-processor
      auto-offset-reset: earliest
  data:
    mongodb:
      auto-index-creation: true

app:
  kafka:
    topic: am-document-topic
  persistence:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/nse_security?authSource=admin
      database: nse_security

logging:
  level:
    root: INFO
    org.am.mypotrfolio: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
    org.hibernate.SQL: INFO
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.springframework.data.mongodb.core.MongoTemplate]': DEBUG