{{- if .Values.ingress.enabled -}}
{{- $fullName := printf "%s-route" (include "am-document-processor.fullname" .) -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
spec:
  http:
    - name: {{ $fullName }}
      match:
        hosts:
          - {{ .Values.ingress.host | default "test.local" | quote }}
        paths:
          - /*
      backends:
        - serviceName: {{ include "am-document-processor.fullname" . }}-service
          servicePort: {{ $svcPort }}
{{- end }}
