{{- if .Values.ingress.enabled -}}
{{- $fullName := printf "%s-route" (include "am-document-processor.fullname" .) -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
spec:
  http:
    - name: {{ $fullName }}-root
      match:
        hosts:
          - {{ .Values.ingress.host | default "test.local" | quote }}
        paths:
          - /
      backends:
        - serviceName: {{ include "am-document-processor.fullname" . }}-service
          servicePort: {{ $svcPort }}
      plugins:
        - name: response-rewrite
          config:
            headers:
              set:
                X-Debug-Route: "root-path"
    - name: {{ $fullName }}-swagger-ui
      match:
        hosts:
          - {{ .Values.ingress.host | default "test.local" | quote }}
        paths:
          - /swagger-ui/*
      backends:
        - serviceName: {{ include "am-document-processor.fullname" . }}-service
          servicePort: {{ $svcPort }}
      plugins:
        - name: proxy-rewrite
          config:
            regex_uri: ["^/swagger-ui/(.*)", "/swagger-ui/$1"]
        - name: response-rewrite
          config:
            headers:
              set:
                X-Debug-Route: "swagger-ui-path"
    - name: {{ $fullName }}-api
      match:
        hosts:
          - {{ .Values.ingress.host | default "test.local" | quote }}
        paths:
          - /api/*
      backends:
        - serviceName: {{ include "am-document-processor.fullname" . }}-service
          servicePort: {{ $svcPort }}
    - name: {{ $fullName }}-actuator
      match:
        hosts:
          - {{ .Values.ingress.host | default "test.local" | quote }}
        paths:
          - /actuator/*
      backends:
        - serviceName: {{ include "am-document-processor.fullname" . }}-service
          servicePort: {{ $svcPort }}
{{- end }}
