{{- if and .Values.ingress.enabled .Values.ingress.useStandardIngress -}}
{{- $fullName := printf "%s-ingress" (include "am-document-processor.fullname" .) -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "apisix"
spec:
  ingressClassName: apisix
  rules:
    - host: {{ .Values.ingress.host | default "test.local" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "am-document-processor.fullname" . }}-service
                port:
                  number: {{ $svcPort }}
{{- end }}
