name: Maven Publish

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: GITHUB_PACKAGES_USERNAME
          server-password: GITHUB_PACKAGES_TOKEN
          settings-path: ${{ github.workspace }}

      # Copy settings.xml from repo
      - name: Setup Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cp settings.xml ~/.m2/settings.xml

      # Set version using GitHub run ID
      - name: Set version with GitHub run ID
        run: mvn versions:set -DnewVersion=v${{ github.run_id }}

      # Build and publish with Maven
      - name: Build and publish with Maven
        run: mvn -B deploy
        env:
          GITHUB_PACKAGES_USERNAME: ${{ github.actor }}
          GITHUB_PACKAGES_TOKEN: ${{ github.token }}
          
      # Save artifact information
      - name: Save artifact info
        run: |
          echo "Artifact: org.am:am-processor:v${{ github.run_id }}" > artifact-info.txt
          
      - name: Upload artifact info
        uses: actions/upload-artifact@v4
        with:
          name: artifact-info
          path: artifact-info.txt
          retention-days: 1

  # Trigger deployment workflow if needed
  deploy:
    needs: build-and-publish
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/unified-deployment.yml
    with:
      image_tag: v${{ github.run_id }}
    secrets: inherit
